language: bash

services:
  - docker

env:
  global:
    - IMAGE_NAME=${pgkar}/wahlzeit
    - IMAGE_NAME_TAGGED=${pgkar}/wahlzeit:${homework03}

script:
  - docker build -t ${IMAGE_NAME} .

deploy:
  - provider: script
    script: 
      docker login -u ${pgkar} -p ${Parham75*} && docker push ${wahlzeit}
    on:
      branch: master
  
  - provider: script
    script: docker login -u ${pgkar} -p ${Parham75*} && docker tag ${wahlzeit} ${wahlzeit:homework03} && docker push ${wahlzeit:homework03}
    on:
      tags: true
